#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

[[layers]]
name='lsp'
filetypes = ["cpp"]    
enabled_clients = ['clangd']
enable = true


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

#Fuzzy
[[layers]]
name = "unite"

#C++/C
[[layers]]
name = 'lang#c'
autocomplete_method='deoplete'

#Tagging
[[layers]]
name = "gtags"

#Linting
[[layers]]
name = "checkers"

#Python
[[layers]]
name = "lang#python"

#Markdown
[[layers]]
name = "lang#markdown"

#Code Formatting
[[layers]]
  name = "format"

#Treesitter layer
[[layers]]
name="treesitter"
#Atom Colorcheme
[[custom_plugins]]
repo="https://github.com/joshdick/onedark.vim"

[options]
colorscheme="onedark"

# VCS
#[[layers]]
#  name = "VersionControl"


#Icons
[[custom_plugins]]
repo="https://github.com/ryanoasis/vim-devicons"

#Colorizer
[[custom_plugins]]
repo="https://github.com/norcalli/nvim-colorizer.lua"
hook_add = '''
  lua << EOF
  vim.opt.termguicolors = true
  require 'colorizer'.setup {
  '*'; -- Highlight all files, but customize some others.
  '!vim'; -- Exclude vim from highlighting.
  -- Exclusion Only makes sense if '*' is specified!
}
EOF
'''
#Treesitter
[[custom_plugins]]
repo="https://github.com/nvim-treesitter/nvim-treesitter"

[[custom_plugins]]
repo="https://github.com/ton/vim-alternate"


Markdown Viewer
[[custom_plugins]]
repo="https://github.com/iamcco/markdown-preview.nvim"

