#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true
clang_executable="/usr/lib/clang"

#Fuzzy
[[layers]]
name = "unite"

#C++/C
[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true
libclang_path='$HOME/.local/lib/python3.8/site-packages/clang/native/libclang.so'

#Python
[[layers]]
name = "lang#python"


[[custom_plugins]]
repo="https://github.com/ryanoasis/vim-devicons"

[[custom_plugins]]
repo="https://github.com/joshdick/onedark.vim"
[options]
colorscheme="onedark"

#Linting
[[layers]]
name = "checkers"
