# [build]
# command="qnx_71_toolchain && build"
# isBackground= false
#
# [package]
# command="qnx_71_toolchain && package"
# isBackground= false
#
# [package]
# command="qnx_71_toolchain && package && install"
# isBackground= false
#
# [install]
# command="qnx_71_toolchain && install"
# isBackground= false

[qnx71_toolchain]
command="qnx_71_toolchain"
isBackground= false


[build71]
command="qnx_71_toolchain && build 7.1"
isBackground= false

[build70]
command="qnx_70_toolchain && build 7.0"
isBackground= false

[package71]
command="qnx_71_toolchain && package 7.1"
isBackground= false

[package70]
command="qnx_70_toolchain && package 7.0"
isBackground= false

[install]
command="qnx_71_toolchain && install"
isBackground= false

# [ntoaarch64_executable]
# command="qnx_71_toolchain && ntoaarch64"
# args=['linefollower.c', '-o', 'linefollower_v2', '-lspi-master' ]
# isBackground= false

